# -*- coding: utf-8 -*-
"""smac pymarl.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RC5Gd1GVEYfYLAHFsDTwVtA5Qdmap0nI
"""

# @title 1. 构建 Python 3.12虚拟环境
!pip install -q condacolab
import condacolab
condacolab.install()

# @title 2.环境一键安装 (SMACv1 稳定版)
import os
import sys

!conda install -y pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia
!pip install -q sacred==0.8.2 numpy==1.23.5 scipy==1.9.3 matplotlib py-cpuinfo tensorboard_logger pygame PyYAML

# SMAC接口
!pip install git+https://github.com/oxwhirl/smac.git

# 星际II引擎
sc2_executable_path = "/content/StarCraftII/Versions/Base75689/SC2_x64"
if not os.path.exists(sc2_executable_path):
    print("StarCraft II 核心文件缺失或损坏")
    if os.path.exists("/content/StarCraftII"):
        !rm -rf /content/StarCraftII
        print("旧的 StarCraftII 目录已清除。")

    print("正在下载星际II引擎(约3.8GB)")
    !wget -q http://blzdistsc2-a.akamaihd.net/Linux/SC2.4.10.zip
    !echo "iagreetotheeula" | 7z x SC2.4.10.zip -piagreetotheeula -o/content/ > /dev/null
    !rm SC2.4.10.zip
    !chmod -R 777 /content/StarCraftII
    !chmod +x {sc2_executable_path}
    print("StarCraftII引擎配置完成。")
else:
    print("StarCraftII引擎已就绪。")

# SMAC地图集
!mkdir -p /content/StarCraftII/Maps
if not os.path.exists("/content/StarCraftII/Maps/3m.SC2Map"):
    !wget -q https://github.com/oxwhirl/smac/raw/master/smac/env/starcraft2/maps/SMAC_Maps.zip
    !unzip -q -o SMAC_Maps.zip -d /content/StarCraftII/Maps/
    !rm SMAC_Maps.zip
    print("SMAC地图集已就绪。")
else:
    print("SMAC地图集已存在。")

os.environ['SC2PATH'] = '/content/StarCraftII'
print("环境全部就绪！")

# Commented out IPython magic to ensure Python compatibility.
# @title  2.5 下载 PyMARL 核心仓库
import os
# %rm -rf /content/pymarl
# %cd /content
if not os.path.exists("/content/pymarl"):
    # 克隆官方仓库
    !git clone https://github.com/oxwhirl/pymarl.git
    print("载完成！")
else:
    print("文件夹已存在。")

!ls -l /content/pymarl/src

# @title  3. 修复 PyMARL 的 main.py 代码兼容性问题
import os

main_py_path = "/content/pymarl/src/main.py"
print(f"检查并修复文件: {main_py_path}")

if not os.path.exists(main_py_path):
    print(f"文件{main_py_path}不存在。")
else:
    with open(main_py_path, 'r') as f:
        content = f.read()
    original_content = content
    # 修复 collections.Mapping报错
    mapping_patch_str = """import collections
try:
    from collections.abc import Mapping
except ImportError:
    from collections import Mapping
collections.Mapping = Mapping
"""
    # 检查是否已存在补丁
    if "collections.Mapping = Mapping" not in content:
        content = mapping_patch_str + content
        print("已应用collections.Mapping兼容性补丁。")
    else:
        print("collections.Mapping补丁已存在。")

    # 修复yaml.load报错
    old_yaml_load_str = "yaml.load(f)"
    new_yaml_load_str = "yaml.load(f, Loader=yaml.FullLoader)"

    if old_yaml_load_str in content and new_yaml_load_str not in content:
        content = content.replace(old_yaml_load_str, new_yaml_load_str)
        print("已应用 yaml.load(f, Loader=yaml.FullLoader) 补丁。")
    elif new_yaml_load_str in content:
        print("yaml.load(f, Loader=yaml.FullLoader) 补丁已存在。")
    else:
        print("main.py 中未找到 'yaml.load(f)'。")

    if content != original_content:
        with open(main_py_path, 'w') as f:
            f.write(content)
        print("main.py代码兼容性修复已完成")
    else:
        print("main.py文件内容未发生变化。")
    print("\n--- main.py修复后相关代码片段预览")
    with open(main_py_path, 'r') as f:
        lines = f.readlines()
        for i, line in enumerate(lines):
            if i < 10 or ("yaml.load" in line and "Loader=yaml.FullLoader" in line) or ("collections.Mapping = Mapping" in line):
                print(f"Line {i+1}: {line.strip()}")

# @title 4. 强力重置并对齐地图
import os
import shutil

# 1. 定义源路径和目标路径
base_path = "/content/StarCraftII"
smac_maps_dest = os.path.join(base_path, "Maps/SMAC_Maps")

# 2. 创建目标文件夹
os.makedirs(smac_maps_dest, exist_ok=True)

# 3. 寻找并移动地图文件
# 检查 pymarl 仓库里自带的地图（如果有）
# pymarl_map_src = "/content/pymarl/src/envs/starcraft2/maps/SMAC_Maps"

# if os.path.exists(pymarl_map_src):
#     print("🚀 正在从 PyMARL 复制地图到星际目录...")
#     for map_file in os.listdir(pymarl_map_src):
#         if map_file.endswith(".SC2Map"):
#             shutil.copy(os.path.join(pymarl_map_src, map_file), smac_maps_dest)
#     print("✅ 地图复制完成！")
# else:
#     # 如果仓库里没带，尝试从整个磁盘搜索 3m.SC2Map
#     print("🔍 正在搜索地图文件...")
#     !find /content -name "3m.SC2Map" -exec cp {} $smac_maps_dest \;
#     print("✅ 搜索并对齐完成！")

# 4. 验证地图是否存在
if os.path.exists(os.path.join(smac_maps_dest, "3m.SC2Map")):
    print("🌟 确认成功：3m.SC2Map 已就位！")
else:
    print("⚠️ 还是没找到地图，正在尝试从官方源直接下载...")
    !wget https://github.com/oxwhirl/smac/raw/master/smac/env/starcraft2/maps/SMAC_Maps/3m.SC2Map -P $smac_maps_dest

# @title 5. 补齐 Sacred 运行依赖
!pip install setuptools==69.5.1 munch -q
import pkg_resources
print("✅ pkg_resources 已找回，Sacred 现在可以正常运行了！")

# @title 6. 修复 PyYAML 兼容性补丁
import os

main_py_path = "/content/pymarl/src/main.py"

if os.path.exists(main_py_path):
    with open(main_py_path, 'r') as f:
        content = f.read()

    # 将旧的 yaml.load(f) 替换为安全的 FullLoader 模式
    if 'yaml.load(f)' in content:
        new_content = content.replace('yaml.load(f)', 'yaml.load(f, Loader=yaml.FullLoader)')
        with open(main_py_path, 'w') as f:
            f.write(new_content)
        print("✅ 成功修复 main.py 中的 YAML 加载报错！")
    else:
        print("💡 补丁似乎已经打过了，或者代码结构不同。")
else:
    print("❌ 找不到 main.py，请确认是否已执行 git clone 下载了代码。")

# @title 7. 修复Logger的CUDA兼容性补丁
import os

log_py_path = "/content/pymarl/src/utils/logging.py"

if os.path.exists(log_py_path):
    with open(log_py_path, 'r') as f:
        lines = f.readlines()

    new_lines = []
    found = False
    for line in lines:
        if "np.mean([x[1] for x in self.stats[k][-window:]])" in line:
            new_line = line.replace(
                "np.mean([x[1] for x in self.stats[k][-window:]])",
                "np.mean([x[1].item() if hasattr(x[1], 'item') else x[1] for x in self.stats[k][-window:]])"
            )
            new_lines.append(new_line)
            found = True
        else:
            new_lines.append(line)

    if found:
        with open(log_py_path, 'w') as f:
            f.writelines(new_lines)
        print("修复logging.py中的CUDA->NumPy转换报错")
    else:
        print("补丁已打过。")
else:
    print("找不到logging.py")

# @title 8. 一键下载并安装完整的 SMAC 地图包
import os

# 1. 确保目标文件夹存在
!mkdir -p /content/StarCraftII/Maps

# 2. 下载官方完整的 SMAC 地图压缩包
!wget https://github.com/oxwhirl/smac/releases/download/v0.1-beta1/SMAC_Maps.zip

# 3. 解压到星际争霸的 Maps 目录下
!unzip -q -o SMAC_Maps.zip -d /content/StarCraftII/Maps/

# 4. 删除压缩包节省空间
!rm SMAC_Maps.zip

print("✅ 所有 SMAC 官方地图已成功安装！包含 5m_vs_6m, MMM2 等。")

# @title 9.1【QMIX 基线测试】一键训练 + 画图 + 录像 + 网盘备份
import os
import glob
import shutil
import subprocess
import matplotlib.pyplot as plt
from tensorboard.backend.event_processing.event_accumulator import EventAccumulator
from google.colab import drive


MAP_NAME = "3s5z"      # 3m,8m,2s3z,MMM2,5m_vs_6m,3s5z
T_MAX = 1000000
SAVE_INTERVAL = 99000
ALG_PREFIX = f"qmix_{MAP_NAME}

print(f"连接Google Drive，执行{MAP_NAME}地图的QMIX测试")
drive.mount('/content/drive')
backup_base = "/content/drive/MyDrive/毕设MARL备份"
os.makedirs(f"{backup_base}/Plots", exist_ok=True)
os.makedirs(f"{backup_base}/Replays/{MAP_NAME}", exist_ok=True)
os.makedirs(f"{backup_base}/Models_and_Logs", exist_ok=True)

print(f"\n [1/4] 开始训练原版QMIX(地图:{MAP_NAME})")

env_vars = os.environ.copy()
env_vars["SC2PATH"] = "/content/StarCraftII"

train_cmd = f"""cd /content/pymarl/src && python3 main.py --config=qmix --env-config=sc2 with \
    env_args.map_name={MAP_NAME} \
    t_max={T_MAX} \
    name="{ALG_PREFIX}" \
    use_tensorboard=True \
    save_model=True \
    save_model_interval={SAVE_INTERVAL}
"""

process = subprocess.Popen(train_cmd, shell=True, env=env_vars, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
for line in process.stdout:
    print(line, end='')
process.wait()

print(f"{MAP_NAME}地图的QMIX训练完成")

print("\n[2/4] 解析TensorBoard绘制胜率曲线")
tb_paths = glob.glob(f"/content/pymarl/**/tb_logs/{ALG_PREFIX}*", recursive=True)
if tb_paths:
    latest_tb = max(tb_paths, key=os.path.getmtime)
    ea = EventAccumulator(latest_tb)
    ea.Reload()
    if 'test_battle_won_mean' in ea.scalars.Keys():
        events = ea.scalars.Items('test_battle_won_mean')
        steps = [e.step for e in events]
        vals = [e.value for e in events]

        plt.figure(figsize=(8, 5))
        plt.plot(steps, vals, label=f'QMIX ({MAP_NAME})', color='#1f77b4', linewidth=2.5)
        plt.title(f'Win Rate Convergence on{MAP_NAME}(QMIX Baseline)', fontsize=14)
        plt.xlabel('Environment Steps', fontsize=12)
        plt.ylabel('Test Battle Won Mean', fontsize=12)
        plt.ylim(-0.05, 1.05)
        plt.grid(True, linestyle='--', alpha=0.7)
        plt.legend(loc='lower right')

        plot_path = f"{backup_base}/Plots/QMIX_{MAP_NAME}_win_rate.png"
        plt.savefig(plot_path, dpi=300, bbox_inches='tight')
        plt.show()
        print(f"图表已安全存入网盘:{plot_path}")
    else:
        print("未能在日志中找到test_battle_won_mean字段。")

print(f"\n[3/4] 正在提取{MAP_NAME}地图的历史存档，生成录像...")
model_paths = glob.glob(f"/content/pymarl/**/models/{ALG_PREFIX}*", recursive=True)
if model_paths:
    latest_model_dir = max(model_paths, key=os.path.getmtime)
    step_folders = [d for d in os.listdir(latest_model_dir) if d.isdigit()]
    step_folders.sort(key=int)

    print(f"检测到以下检查点:{step_folders}")
    for step in step_folders:
        print(f"在生成第{step}步的回放...")
        eval_cmd = f"""cd /content/pymarl/src && python3 main.py --config=qmix --env-config=sc2 with \
            env_args.map_name={MAP_NAME} \
            evaluate=True \
            save_replay=True \
            test_nepisode=1 \
            checkpoint_path="{latest_model_dir}" \
            load_step={step}
        """
        subprocess.run(eval_cmd, shell=True, env=env_vars, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        replays = glob.glob("/content/StarCraftII/Replays/**/*.SC2Replay", recursive=True)
        for rp in replays:
            # 文件名加入地图名和步数，防止混淆
            new_name = f"QMIX_{MAP_NAME}_step_{step}.SC2Replay"
            dest_path = os.path.join(backup_base, "Replays", MAP_NAME, new_name)
            shutil.copy(rp, dest_path)
            os.remove(rp)
    print("该地图的所有录像已分类打包至网盘")

print("\n[4/4]正在将底层日志和原始模型深度备份到Google Drive")
src_results = "/content/pymarl/results"
dest_results = f"{backup_base}/Models_and_Logs"
if os.path.exists(src_results):
    shutil.copytree(src_results, dest_results, dirs_exist_ok=True)

print(f"\n{MAP_NAME}地图QMIX测试完成")

# @title 从网盘备份加载QMIX训练日志并绘制胜率曲线
import os
import glob
import matplotlib.pyplot as plt
from tensorboard.backend.event_processing.event_accumulator import EventAccumulator
from google.colab import drive

# 配置参数（请根据实际情况修改）
MAP_NAME = "3s5z"          # 与训练时一致
ALG_PREFIX = f"qmix_{MAP_NAME}"
BACKUP_ROOT = "/content/drive/MyDrive/毕设MARL备份"

# 挂载Google Drive
drive.mount('/content/drive')

# 定位TensorBoard日志目录（备份时保存在Models_and_Logs下）
log_base = os.path.join(BACKUP_ROOT, "Models_and_Logs")
tb_pattern = f"{log_base}/**/tb_logs/{ALG_PREFIX}*"
tb_paths = glob.glob(tb_pattern, recursive=True)

if not tb_paths:
    raise FileNotFoundError(f"未找到匹配的日志：{tb_pattern}")

# 使用最新的日志目录
latest_tb = max(tb_paths, key=os.path.getmtime)
print(f"使用日志：{latest_tb}")

# 解析TensorBoard事件
ea = EventAccumulator(latest_tb)
ea.Reload()

if 'test_battle_won_mean' not in ea.scalars.Keys():
    raise KeyError("日志中缺少test_battle_won_mean指标")

events = ea.scalars.Items('test_battle_won_mean')
steps = [e.step for e in events]
values = [e.value for e in events]

# 绘制胜率曲线
plt.figure(figsize=(8, 5))
plt.plot(steps, values, label=f'QMIX ({MAP_NAME})', color='#1f77b4', linewidth=2.5)
plt.title(f'QMIX在{MAP_NAME}地图上的胜率收敛曲线', fontsize=14)
plt.xlabel('环境步数', fontsize=12)
plt.ylabel('测试胜率', fontsize=12)
plt.ylim(-0.05, 1.05)
plt.grid(True, linestyle='--', alpha=0.7)
plt.legend(loc='lower right')

# 保存图片到备份目录下的Plots文件夹（也可显示）
output_dir = os.path.join(BACKUP_ROOT, "Plots")
os.makedirs(output_dir, exist_ok=True)
plot_path = os.path.join(output_dir, f"QMIX_{MAP_NAME}_win_rate_from_backup.png")
plt.savefig(plot_path, dpi=300, bbox_inches='tight')
print(f"图片已保存至：{plot_path}")

plt.show()

# Commented out IPython magic to ensure Python compatibility.
# 第1步：挂载Google Drive
from google.colab import drive
drive.mount('/content/drive')

# 第2步：指定备份根目录（与你之前训练时的备份路径一致）
BACKUP_ROOT = "/content/drive/MyDrive/毕设MARL备份"

# 第3步：找到TensorBoard日志所在的子目录（通常在 Models_and_Logs/tb_logs/ 下）
import glob
import os

# 根据你训练时设定的 ALG_PREFIX 来匹配，例如 qmix_3s5z
MAP_NAME = "3s5z"   # 可修改
ALG_PREFIX = f"qmix_{MAP_NAME}"

log_dir_candidate = f"{BACKUP_ROOT}/Models_and_Logs/**/tb_logs/{ALG_PREFIX}*"
tb_dirs = glob.glob(log_dir_candidate, recursive=True)

if not tb_dirs:
    raise FileNotFoundError(f"未在备份中找到匹配的日志目录：{log_dir_candidate}")

# 使用最新的日志目录（按修改时间）
latest_tb_dir = max(tb_dirs, key=os.path.getmtime)
print(f"找到TensorBoard日志：{latest_tb_dir}")

# 第4步：启动TensorBoard
# %load_ext tensorboard
# %tensorboard --logdir {latest_tb_dir}

# @title 9.2【QMIX 基线测试2】一键训练 + 画图 + 录像 + 网盘备份
import os
import glob
import shutil
import subprocess
import matplotlib.pyplot as plt
from tensorboard.backend.event_processing.event_accumulator import EventAccumulator
from google.colab import drive

# ==========================================
# 🎯 核心参数配置区 (测试不同地图只需改这里)
# ==========================================
MAP_NAME = "MMM2"      # 要测试的地图: 3m, 8m, 2s3z, MMM2, 5m_vs_6m 等
T_MAX = 1000000             # 训练总步数 (困难地图调大到 1000000 或 2000000)
SAVE_INTERVAL = 100000     # 每隔多少步保存一次模型并录制一次回放
ALG_PREFIX = f"qmix_{MAP_NAME}" # 自动生成的实验前缀，防止不同地图数据混淆

# ==========================================
# 0. 挂载 Google Drive 并建立分类文件夹
# ==========================================
print(f"📂 正在连接 Google Drive，准备执行 {MAP_NAME} 地图的 QMIX 测试...")
drive.mount('/content/drive')
backup_base = "/content/drive/MyDrive/毕设MARL备份"
os.makedirs(f"{backup_base}/Plots", exist_ok=True)
os.makedirs(f"{backup_base}/Replays/{MAP_NAME}", exist_ok=True) # 按地图分类存放录像
os.makedirs(f"{backup_base}/Models_and_Logs", exist_ok=True)
print(f"✅ 网盘挂载成功！数据将实时同步。")

# ==========================================
# 1. 执行训练 (实时显示日志)
# ==========================================
print(f"\n🏃‍♂️ [1/4] 开始训练原版 QMIX (地图: {MAP_NAME})...")
print("👀 提示：训练日志将实时输出，请关注 t_env 和 test_battle_won_mean！\n")
print("-" * 50)

env_vars = os.environ.copy()
env_vars["SC2PATH"] = "/content/StarCraftII"

train_cmd = f"""cd /content/pymarl/src && python3 main.py --config=qmix --env-config=sc2 with \
    env_args.map_name={MAP_NAME} \
    t_max={T_MAX} \
    name="{ALG_PREFIX}" \
    use_tensorboard=True \
    save_model=True \
    save_model_interval={SAVE_INTERVAL}
"""

# 使用 Popen 实时流式读取终端输出
process = subprocess.Popen(train_cmd, shell=True, env=env_vars, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
for line in process.stdout:
    print(line, end='')
process.wait()

print("-" * 50)
print(f"✅ {MAP_NAME} 地图的 QMIX 训练正式完成！")

# ==========================================
# 2. 自动提取数据画图，并直传网盘
# ==========================================
print("\n📈 [2/4] 正在解析 TensorBoard 绘制胜率曲线...")
tb_paths = glob.glob(f"/content/pymarl/**/tb_logs/{ALG_PREFIX}*", recursive=True)
if tb_paths:
    latest_tb = max(tb_paths, key=os.path.getmtime)
    ea = EventAccumulator(latest_tb)
    ea.Reload()
    if 'test_battle_won_mean' in ea.scalars.Keys():
        events = ea.scalars.Items('test_battle_won_mean')
        steps = [e.step for e in events]
        vals = [e.value for e in events]

        plt.figure(figsize=(8, 5))
        plt.plot(steps, vals, label=f'QMIX ({MAP_NAME})', color='#1f77b4', linewidth=2.5)
        plt.title(f'Win Rate Convergence on {MAP_NAME} (QMIX Baseline)', fontsize=14)
        plt.xlabel('Environment Steps', fontsize=12)
        plt.ylabel('Test Battle Won Mean', fontsize=12)
        plt.ylim(-0.05, 1.05)
        plt.grid(True, linestyle='--', alpha=0.7)
        plt.legend(loc='lower right')

        plot_path = f"{backup_base}/Plots/QMIX_{MAP_NAME}_win_rate.png"
        plt.savefig(plot_path, dpi=300, bbox_inches='tight')
        plt.show()
        print(f"✅ 图表已安全存入网盘: {plot_path}")
    else:
        print("⚠️ 未能在日志中找到 test_battle_won_mean 字段。")

# ==========================================
# 3. 遍历所有保存的节点，生成“进化录像”
# ==========================================
print(f"\n🎥 [3/4] 正在提取 {MAP_NAME} 地图的历史存档，生成录像...")

model_paths = glob.glob(f"/content/pymarl/**/models/{ALG_PREFIX}*", recursive=True)
if model_paths:
    latest_model_dir = max(model_paths, key=os.path.getmtime)
    step_folders = [d for d in os.listdir(latest_model_dir) if d.isdigit()]
    step_folders.sort(key=int)

    print(f"🔍 检测到以下检查点: {step_folders}")
    for step in step_folders:
        print(f"   ▶️ 正在生成第 {step} 步的回放...")
        eval_cmd = f"""cd /content/pymarl/src && python3 main.py --config=qmix --env-config=sc2 with \
            env_args.map_name={MAP_NAME} \
            evaluate=True \
            save_replay=True \
            test_nepisode=1 \
            checkpoint_path="{latest_model_dir}" \
            load_step={step}
        """
        subprocess.run(eval_cmd, shell=True, env=env_vars, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

        replays = glob.glob("/content/StarCraftII/Replays/**/*.SC2Replay", recursive=True)
        for rp in replays:
            # 文件名加入地图名和步数，防止混淆
            new_name = f"QMIX_{MAP_NAME}_step_{step}.SC2Replay"
            dest_path = os.path.join(backup_base, "Replays", MAP_NAME, new_name)
            shutil.copy(rp, dest_path)
            os.remove(rp)
    print("✅ 该地图的所有录像已分类打包至网盘！")

# ==========================================
# 4. 增量备份底层模型与日志到 Drive
# ==========================================
print("\n💾 [4/4] 正在将底层日志和原始模型深度备份到 Google Drive...")
src_results = "/content/pymarl/results"
dest_results = f"{backup_base}/Models_and_Logs"
if os.path.exists(src_results):
    shutil.copytree(src_results, dest_results, dirs_exist_ok=True)

print(f"\n🎉 {MAP_NAME} 地图 QMIX 测试全部完美结束！")

# Commented out IPython magic to ensure Python compatibility.
# @title 9.0 QMIX 官方启动器 (内置 WandB 授权)
import os

# 1.Key
clean_key = "Rz43gaI4n7c6DxJtsxJE37AiSwU_AYY6GzwJmA7q"

# 2. 设置环境变量
os.environ["WANDB_API_KEY"] = "Rz43gaI4n7c6DxJtsxJE37AiSwU_AYY6GzwJmA7qfbkCKhaQsyfOXjyVkCWMYmhMTgzPFNm3tzTFC"
os.environ["WANDB_PROJECT"] = "QMIX_Study"
os.environ["WANDB_ENTITY"] = "lys3168418374"
os.environ['SC2PATH'] = '/content/StarCraftII'

# 3. 补齐 Sacred 可能丢失的工具 (pkg_resources)
!pip install setuptools==69.5.1 munch -q

# 4. 进入源码目录
# %cd /content/pymarl/src

# 5. 前台启动训练
# PyMARL 会自动检测到环境变量里的 WANDB_API_KEY
!python3 main.py --config=qmix --env-config=sc2 with \
    env_args.map_name=5m_vs_6m \
    t_max=500000 \
    use_tensorboard=True \
    save_model=True

# Commented out IPython magic to ensure Python compatibility.
# @title  TensorBoard 论文出图工具
# %load_ext tensorboard
# %tensorboard --logdir /content/pymarl/results/tb_logs

# @title 物理备份：下载实验数据到本地
import shutil
from google.colab import files

# 将结果文件夹打包
shutil.make_archive('/content/my_qmix_results', 'zip', '/content/pymarl/results')

# 触发浏览器下载
files.download('/content/my_qmix_results.zip')
print("✅ 数据已打包！请留意浏览器下载弹窗。")

# @title 9.修复 q_learner.py 中的 XMIX 注册
import re

learner_path = "/content/pymarl/src/learners/q_learner.py"

with open(learner_path, "r", encoding="utf-8") as f:
    content = f.read()

# 1. 确保导入了 XMixer
if "from modules.mixers.xmix import XMixer" not in content:
    # 寻找 qmix 导入的位置并在其后追加
    content = re.sub(
        r"(from modules\.mixers\.qmix import QMixer)",
        r"\1\nfrom modules.mixers.xmix import XMixer",
        content
    )

# 2. 确保在 if-elif 分支中实例化了 XMixer
if "elif args.mixer == \"xmix\":" not in content:
    # 寻找 qmix 的实例化位置并在其后追加 xmix 的实例化
    # 注意处理缩进
    replacement = """elif args.mixer == "qmix":
            self.mixer = QMixer(args)
        elif args.mixer == "xmix":
            self.mixer = XMixer(args)"""

    # 替换原有的 qmix 分支
    content = re.sub(
        r"elif args\.mixer == [\'\"]qmix[\'\"]:\s*self\.mixer = QMixer\(args\)",
        replacement,
        content
    )

with open(learner_path, "w", encoding="utf-8") as f:
    f.write(content)

print("✅ XMixer 现已成功强制注册到 q_learner.py！")
# @title 🩹 修复 Sacred 库在 Python 3.11 下的堆栈打印 Bug
!sed -i 's/current_tb = tb_exception.exc_traceback/current_tb = getattr(tb_exception, "exc_traceback", None) or getattr(tb_exception, "__traceback__", None)/g' /usr/local/lib/python3.11/site-packages/sacred/utils.py
!echo "✅ Sacred 库 Python 3.11 兼容性补丁应用成功！"

# @title 10. 构建 XMIX 核心组件与配置
import os

# 1. 创建 xmix.py 核心文件
xmix_code = """import torch as th
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

class XMixer(nn.Module):
    def __init__(self, args):
        super(XMixer, self).__init__()
        self.args = args
        self.n_agents = args.n_agents
        self.state_dim = int(np.prod(args.state_shape))
        self.embed_dim = args.mixing_embed_dim
        self.attn_heads = getattr(args, "attn_heads", 4)

        # 状态嵌入映射
        self.state_embed = nn.Linear(self.state_dim, self.embed_dim * self.n_agents)

        # 多头注意力层 (核心改进：用于提取全局状态中实体交互的上下文特征)
        self.attn = nn.MultiheadAttention(embed_dim=self.embed_dim, num_heads=self.attn_heads, batch_first=True)

        # 接收 Attention Context 的超网络
        self.hyper_w_1 = nn.Linear(self.embed_dim, self.embed_dim * self.n_agents)
        self.hyper_w_2 = nn.Linear(self.embed_dim, self.embed_dim)

        self.hyper_b_1 = nn.Linear(self.state_dim, self.embed_dim)
        self.hyper_b_2 = nn.Sequential(nn.Linear(self.state_dim, self.embed_dim),
                                       nn.ReLU(),
                                       nn.Linear(self.embed_dim, 1))

    def forward(self, agent_qs, states):
        bs = agent_qs.size(0)
        states = states.reshape(-1, self.state_dim)
        agent_qs = agent_qs.view(-1, 1, self.n_agents)

        # --- 注意力机制处理 ---
        state_emb = self.state_embed(states).view(-1, self.n_agents, self.embed_dim)
        attn_out, _ = self.attn(state_emb, state_emb, state_emb)
        global_ctx = attn_out.mean(dim=1) # 聚合为全局特征

        # --- 动态权重生成 ---
        w1 = th.abs(self.hyper_w_1(global_ctx))
        w1 = w1.view(-1, self.n_agents, self.embed_dim)
        b1 = self.hyper_b_1(states).view(-1, 1, self.embed_dim)

        hidden = F.elu(th.bmm(agent_qs, w1) + b1)

        w2 = th.abs(self.hyper_w_2(global_ctx))
        w2 = w2.view(-1, self.embed_dim, 1)
        b2 = self.hyper_b_2(states).view(-1, 1, 1)

        y = th.bmm(hidden, w2) + b2
        q_tot = y.view(bs, -1, 1)

        return q_tot
"""
with open("/content/pymarl/src/modules/mixers/xmix.py", "w") as f:
    f.write(xmix_code)

# 2. 注册 XMIX 到 PyMARL 学习器
learner_path = "/content/pymarl/src/learners/q_learner.py"
with open(learner_path, "r") as f:
    content = f.read()

if "from modules.mixers.xmix import XMixer" not in content:
    content = content.replace("from modules.mixers.qmix import QMixer",
                              "from modules.mixers.qmix import QMixer\nfrom modules.mixers.xmix import XMixer")

if "elif args.mixer == \"xmix\":" not in content:
    old_str = "elif args.mixer == \"qmix\":\n            self.mixer = QMixer(args)"
    new_str = "elif args.mixer == \"qmix\":\n            self.mixer = QMixer(args)\n        elif args.mixer == \"xmix\":\n            self.mixer = XMixer(args)"
    content = content.replace(old_str, new_str)

with open(learner_path, "w") as f:
    f.write(content)

# 3. 创建 xmix.yaml 配置文件
xmix_yaml = """action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000
runner: "episode"
buffer_size: 5000
target_update_interval: 200
agent: "rnn"
mac: "basic_mac"
agent_output_type: "q"
learner: "q_learner"
double_q: True
mixer: "xmix"
mixing_embed_dim: 32
attn_heads: 4
hypernet_embed: 64
name: "xmix"
"""
with open("/content/pymarl/src/config/algs/xmix.yaml", "w") as f:
    f.write(xmix_yaml)

print("✅ XMIX 模型架构与配置文件注入成功！")

# @title 11.修复 q_learner.py 缩进错误
import re

file_path = "/content/pymarl/src/learners/q_learner.py"

with open(file_path, "r", encoding="utf-8") as f:
    content = f.read()

# 匹配从 vdn 到 raise ValueError 的整个 if-elif 代码块，进行精准替换
pattern = re.compile(r'if args\.mixer == "vdn":.*?raise ValueError', re.DOTALL)

# 严格保证 12 个空格的缩进
correct_block = """if args.mixer == "vdn":
                self.mixer = VDNMixer()
            elif args.mixer == "qmix":
                self.mixer = QMixer(args)
            elif args.mixer == "xmix":
                self.mixer = XMixer(args)
            else:
                raise ValueError"""

if pattern.search(content):
    content = pattern.sub(correct_block, content)
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)
    print("✅ 缩进错误已彻底修复！现在可以重新运行 main.py 了。")
else:
    print("⚠️ 尝试使用备用修复方案...")
    # 针对可能已经被破坏得比较严重的单行进行修复
    content = re.sub(r'^[ \t]*elif args\.mixer == [\'"]qmix[\'"]:', '            elif args.mixer == "qmix":', content, flags=re.MULTILINE)
    content = re.sub(r'^[ \t]*self\.mixer = QMixer\(args\)', '                self.mixer = QMixer(args)', content, flags=re.MULTILINE)
    content = re.sub(r'^[ \t]*elif args\.mixer == [\'"]xmix[\'"]:', '            elif args.mixer == "xmix":', content, flags=re.MULTILINE)
    content = re.sub(r'^[ \t]*self\.mixer = XMixer\(args\)', '                self.mixer = XMixer(args)', content, flags=re.MULTILINE)
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)
    print("✅ 备用缩进修复完成！")

# Commented out IPython magic to ensure Python compatibility.
# @title 12. 启动 XMIX 训练
import os

# 强行阻断可能卡死环境的在线同步组件
os.environ["WANDB_MODE"] = "offline"
os.environ['SC2PATH'] = '/content/StarCraftII'

# %cd /content/pymarl/src
!python3 main.py --config=xmix --env-config=sc2 with \
    env_args.map_name=3m \
    t_max=200000 \
    use_tensorboard=True \
    save_model=True

# Commented out IPython magic to ensure Python compatibility.
# @title 启动 TensorBoard 论文出图工具
# %load_ext tensorboard
# %tensorboard --logdir /content/pymarl/results/tb_logs

# @title 💾 2. 毕设核心数据一键备份下载
import os
import shutil
from google.colab import files

print("🔍 正在收集毕设核心数据...")

backup_dir = "/content/Thesis_Data_Backup"
os.makedirs(backup_dir, exist_ok=True)

# 1. 备份 TensorBoard 绘图原始数据
tb_path = "/content/pymarl/results/tb_logs"
if os.path.exists(tb_path):
    shutil.copytree(tb_path, os.path.join(backup_dir, "tb_logs"), dirs_exist_ok=True)
    print("✅ TensorBoard 日志已收集")

# 2. 备份 Sacred 运行日志 (非常重要！包含配置文件、控制台输出的完整记录)
sacred_path = "/content/pymarl/results/sacred"
if os.path.exists(sacred_path):
    shutil.copytree(sacred_path, os.path.join(backup_dir, "sacred_logs"), dirs_exist_ok=True)
    print("✅ Sacred 实验运行日志已收集")

# 3. 备份之前生成的 Matplotlib 胜率图
png_path = "/content/xmix_win_rate.png"
if os.path.exists(png_path):
    shutil.copy(png_path, backup_dir)
    print("✅ 胜率折线图已收集")

# 4. 打包并下载
zip_path = "/content/Thesis_Data_Backup"
shutil.make_archive(zip_path, 'zip', backup_dir)

print("📦 所有数据已打包完成！正在触发浏览器下载...")
files.download(f"{zip_path}.zip")

# @title 自动加载模型、生成录像并下载
import os
import glob
import subprocess
import shutil
from google.colab import files

# 1. 自动寻找 /content/pymarl/src/results/models/ 下最新的 xmix 模型目录
model_base_dir = "/content/pymarl/src/results/models/"
model_dirs = glob.glob(os.path.join(model_base_dir, "xmix__*"))

if not model_dirs:
    print("❌ 找不到 xmix__ 开头的模型文件夹，请检查目录是否为空。")
else:
    # 按修改时间找到最新的模型文件夹
    latest_model_dir = max(model_dirs, key=os.path.getmtime)
    print(f"🌟 锁定最新模型目录: {latest_model_dir}")

    # 验证该目录下是否有数字命名的步数文件夹 (例如 190184)
    step_dirs = [d for d in os.listdir(latest_model_dir) if d.isdigit()]
    if not step_dirs:
        print(f"❌ 模型目录 {latest_model_dir} 下缺少具体的步数文件夹，请确认训练时是否成功触发保存。")
    else:
        print(f"✅ 检测到存档点: {step_dirs}，开始唤醒星际2引擎进行录像生成...")

        # 2. 构建并执行测试与录制命令
        # evaluate=True: 纯测试模式不训练
        # save_replay=True: 指示 SMAC 保存录像
        cmd = f"""cd /content/pymarl/src && python3 main.py --config=xmix --env-config=sc2 with \\
            env_args.map_name=3m \\
            evaluate=True \\
            save_replay=True \\
            test_nepisode=3 \\
            checkpoint_path="{latest_model_dir}"
        """

        # 设置环境变量，确保正确调用无头星际2客户端
        env = os.environ.copy()
        env["SC2PATH"] = "/content/StarCraftII"

        # 执行命令并捕获输出
        process = subprocess.run(cmd, shell=True, env=env, capture_output=True, text=True)

        # 简单检查输出日志中是否包含测试结束的标志
        if "test_battle_won_mean" in process.stdout or "Finished Training" in process.stdout:
            print("✅ 评估执行完成！模型表现已记录。")
        else:
            print("⚠️ 评估过程可能存在警告，提取关键日志：")
            # 打印最后一部分日志以供排错
            print(process.stdout[-800:])

        # 3. 全局搜索生成的 .SC2Replay 文件并打包下载
        print("🔍 正在搜索生成的录像文件...")
        # SMAC 默认会将录像存放在 StarCraftII/Replays 下
        replay_search_path = "/content/StarCraftII/Replays/**/*.SC2Replay"
        replays = glob.glob(replay_search_path, recursive=True)

        # 备用路径（有时 PyMARL 也会存放在自己的 results 里）
        if not replays:
            replays = glob.glob("/content/pymarl/**/*.SC2Replay", recursive=True)

        if replays:
            print(f"🎉 找到了 {len(replays)} 个回放文件！正在打包...")
            export_dir = "/content/SC2_Replays_Export"
            os.makedirs(export_dir, exist_ok=True)

            # 清理旧文件防止重复打包
            for item in os.listdir(export_dir):
                os.remove(os.path.join(export_dir, item))

            for rp in replays:
                shutil.copy(rp, export_dir)

            # 压缩成 zip 文件
            shutil.make_archive("/content/XMIX_3m_Replays", 'zip', export_dir)
            print("📦 打包完成，正在触发浏览器下载...")
            files.download("/content/XMIX_3m_Replays.zip")
        else:
            print("❌ 未能找到 .SC2Replay 文件，可能是测试局遇到报错未能正常结束。请查看上方输出日志。")

# @title  9. 构建完全符合开题报告的 AMIX 网络与配置
import os
import re

# 1. 创建 attentive_mixer.py
amix_code = """import torch as th
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

class AMixer(nn.Module):
    def __init__(self, args):
        super(AMixer, self).__init__()
        self.args = args
        self.n_agents = args.n_agents
        self.state_dim = int(np.prod(args.state_shape))
        self.embed_dim = getattr(args, "mixing_embed_dim", 64)

        # 消融实验控制开关 (直接读取配置)
        self.attn_heads = getattr(args, "attn_heads", 4)
        self.use_residual = getattr(args, "use_residual", True)
        self.use_layer_norm = getattr(args, "use_layer_norm", True)

        # 状态嵌入
        self.state_embed = nn.Linear(self.state_dim, self.embed_dim * self.n_agents)

        # 多头自注意力层
        self.attn = nn.MultiheadAttention(embed_dim=self.embed_dim, num_heads=self.attn_heads, batch_first=True)

        # 层归一化
        if self.use_layer_norm:
            self.norm1 = nn.LayerNorm(self.embed_dim)
            self.norm2 = nn.LayerNorm(self.embed_dim)

        # 前馈网络 (用于提取特征)
        self.ffn = nn.Sequential(
            nn.Linear(self.embed_dim, self.embed_dim),
            nn.ReLU(),
            nn.Linear(self.embed_dim, self.embed_dim)
        )

        # 保持单调性约束的超网络 (生成非负权重)
        self.hyper_w_1 = nn.Linear(self.embed_dim, self.embed_dim * self.n_agents)
        self.hyper_w_2 = nn.Linear(self.embed_dim, self.embed_dim)
        self.hyper_b_1 = nn.Linear(self.state_dim, self.embed_dim)
        self.hyper_b_2 = nn.Sequential(nn.Linear(self.state_dim, self.embed_dim),
                                       nn.ReLU(),
                                       nn.Linear(self.embed_dim, 1))

    def forward(self, agent_qs, states):
        bs = agent_qs.size(0)
        states = states.reshape(-1, self.state_dim)
        agent_qs = agent_qs.view(-1, 1, self.n_agents)

        # 1. 状态嵌入与注意力机制
        state_emb = self.state_embed(states).view(-1, self.n_agents, self.embed_dim)
        attn_out, _ = self.attn(state_emb, state_emb, state_emb)

        # 残差连接与归一化 (支持消融)
        if self.use_residual:
            attn_out = state_emb + attn_out
        if self.use_layer_norm:
            attn_out = self.norm1(attn_out)

        # 前馈网络处理
        ffn_out = self.ffn(attn_out)
        if self.use_residual:
            ffn_out = attn_out + ffn_out
        if self.use_layer_norm:
            ffn_out = self.norm2(ffn_out)

        # 全局协作表征
        global_ctx = ffn_out.mean(dim=1)

        # 2. 生成单调混合权重 (绝对值保证非负)
        w1 = th.abs(self.hyper_w_1(global_ctx)).view(-1, self.n_agents, self.embed_dim)
        b1 = self.hyper_b_1(states).view(-1, 1, self.embed_dim)
        hidden = F.elu(th.bmm(agent_qs, w1) + b1)

        w2 = th.abs(self.hyper_w_2(global_ctx)).view(-1, self.embed_dim, 1)
        b2 = self.hyper_b_2(states).view(-1, 1, 1)

        y = th.bmm(hidden, w2) + b2
        q_tot = y.view(bs, -1, 1)
        return q_tot
"""
with open("/content/pymarl/src/modules/mixers/attentive_mixer.py", "w") as f:
    f.write(amix_code)

# 2. 注册 AMixer 到 q_learner.py
learner_path = "/content/pymarl/src/learners/q_learner.py"
with open(learner_path, "r", encoding="utf-8") as f:
    content = f.read()

if "from modules.mixers.attentive_mixer import AMixer" not in content:
    content = re.sub(r"(from modules\\.mixers\\.qmix import QMixer)",
                     r"\\1\nfrom modules.mixers.attentive_mixer import AMixer", content)

# This part for mixer registration will be handled by the comprehensive fix below.
# if "elif args.mixer == \"amix\":" not in content:
#     replacement = """elif args.mixer == \"qmix\":\n            self.mixer = QMixer(args)\n        elif args.mixer == \"amix\":\n            self.mixer = AMixer(args)"""
#     content = re.sub(r'elif args\\.mixer == "qmix":\\s*self\\.mixer = QMixer\\(args\\)', replacement, content)

with open(learner_path, "w", encoding="utf-8") as f:
    f.write(content)

# 3. 创建基础 AMIX 配置文件 (完整版)
amix_yaml = """action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000
runner: "episode"
buffer_size: 5000
target_update_interval: 200
agent: "rnn"
mac: "basic_mac"
agent_output_type: "q"
learner: "q_learner"
double_q: True
mixer: "amix"
mixing_embed_dim: 64
attn_heads: 4
use_residual: True
use_layer_norm: True
name: "amix"
"""
with open("/content/pymarl/src/config/algs/amix.yaml", "w") as f:
    f.write(amix_yaml)

print("✅ 正规 AMIX 网络 (支持消融开关) 已部署完毕！")

# @title 🔧 彻底修复 q_learner.py 的所有 Mixer 缩进问题
file_path = "/content/pymarl/src/learners/q_learner.py"

with open(file_path, "r", encoding="utf-8") as f:
    content = f.read()

# This pattern will match the entire block from the first mixer 'if' to the 'raise ValueError'
# It's important to be robust against varying initial indentation of 'if args.mixer == "vdn":'
# So, we capture the initial indentation of the 'if' statement.
# We also ensure it's specifically within a method (e.g., __init__) by looking for 'self.mixer' at expected indent.
pattern = re.compile(r'(\s*)(if args\.mixer == "vdn":(?:\s*self\.mixer = VDNMixer\(\))?)' # Matches 'if vdn' line and optional self.mixer line
                     r'(?:\s*elif args\.mixer == "qmix":\s*self\.mixer = QMixer\(args\))?' # Matches optional 'elif qmix' block
                     r'(?:\s*elif args\.mixer == "xmix":\s*self\.mixer = XMixer\(args\))?' # Matches optional 'elif xmix' block
                     r'(?:\s*elif args\.mixer == "amix":\s*self\.mixer = AMixer\(args\))?' # Matches optional 'elif amix' block
                     r'\s*else:\s*raise ValueError\("Mixer \{\} not recognised\."\.format\(args\.mixer\)\)', re.DOTALL)

match = pattern.search(content)

if match:
    # Extract the original indentation of the 'if' statement
    initial_indent = match.group(1)

    # Construct the correctly indented block using the extracted initial_indent
    # Each level of indentation (4 spaces) is added relative to the initial_indent
    correct_block = f"""{initial_indent}if args.mixer == \"vdn\":
{initial_indent}    self.mixer = VDNMixer()
{initial_indent}elif args.mixer == \"qmix\":
{initial_indent}    self.mixer = QMixer(args)
{initial_indent}elif args.mixer == \"xmix\":
{initial_indent}    self.mixer = XMixer(args)
{initial_indent}elif args.mixer == \"amix\":
{initial_indent}    self.mixer = AMixer(args)
{initial_indent}else:
{initial_indent}    raise ValueError(\"Mixer {{}} not recognised.\".format(args.mixer))"""

    content = pattern.sub(correct_block, content)

    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)
    print("✅ q_learner.py 的所有 Mixer 缩进错误已彻底修复！")
else:
    print("❌ 未找到 Mixer 选择代码块，请检查 q_learner.py 文件结构或手动修复。")

# @title  10. 构建改进版 AMIX 网络与配置（含梯度稳定性优化）

import os
import re

# 1.创建改进后的 attentive_mixer.py
# 核心改进点：th.exp替代th.abs，增加state_embed深度，使用Max Pooling聚合
amix_code = """import torch as th
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

class AMixer(nn.Module):
    def __init__(self, args):
        super(AMixer, self).__init__()
        self.args = args
        self.n_agents = args.n_agents
        self.state_dim = int(np.prod(args.state_shape))
        self.embed_dim = getattr(args, "mixing_embed_dim", 64)

        # 消融实验控制开关
        self.attn_heads = getattr(args, "attn_heads", 4)
        self.use_residual = getattr(args, "use_residual", True)
        self.use_layer_norm = getattr(args, "use_layer_norm", True)

        # 改进的状态嵌入：深层 MLP 更有利于 Attention 提取特征
        self.state_embed = nn.Sequential(
            nn.Linear(self.state_dim, self.embed_dim),
            nn.ReLU(),
            nn.Linear(self.embed_dim, self.embed_dim * self.n_agents)
        )

        # 多头自注意力层
        self.attn = nn.MultiheadAttention(embed_dim=self.embed_dim, num_heads=self.attn_heads, batch_first=True)

        # 规范化层
        if self.use_layer_norm:
            self.norm1 = nn.LayerNorm(self.embed_dim)
            self.norm2 = nn.LayerNorm(self.embed_dim)

        # 前馈网络(用于增强特征非线性)
        self.ffn = nn.Sequential(
            nn.Linear(self.embed_dim, self.embed_dim * 2),
            nn.ReLU(),
            nn.Linear(self.embed_dim * 2, self.embed_dim)
        )

        # 超网络(使用 th.exp 保证严格单调且梯度平滑)
        self.hyper_w_1 = nn.Linear(self.embed_dim, self.embed_dim * self.n_agents)
        self.hyper_w_2 = nn.Linear(self.embed_dim, self.embed_dim)

        self.hyper_b_1 = nn.Linear(self.state_dim, self.embed_dim)
        self.hyper_b_2 = nn.Sequential(
            nn.Linear(self.state_dim, self.embed_dim),
            nn.ReLU(),
            nn.Linear(self.embed_dim, 1)
        )

    def forward(self, agent_qs, states):
        bs = agent_qs.size(0)
        states = states.reshape(-1, self.state_dim)
        agent_qs = agent_qs.view(-1, 1, self.n_agents)

        # 特征提取与 Attention
        # 映射并变形为(batch*T, n_agents, embed_dim)
        state_repr = self.state_embed(states).view(-1, self.n_agents, self.embed_dim)

        attn_out, _ = self.attn(state_repr, state_repr, state_repr)

        if self.use_residual:
            attn_out = state_repr + attn_out
        if self.use_layer_norm:
            attn_out = self.norm1(attn_out)

        ffn_out = self.ffn(attn_out)
        if self.use_residual:
            ffn_out = attn_out + ffn_out
        if self.use_layer_norm:
            ffn_out = self.norm2(ffn_out)

        # 使用Max Pooling捕捉最显著特征
        global_ctx = ffn_out.max(dim=1)[0]

        # 单调混合(QMIX核心逻辑改进)
        # w1 必须非负，使用exp避免abs的导数断点问题
        w1 = th.exp(self.hyper_w_1(global_ctx)).view(-1, self.n_agents, self.embed_dim)
        b1 = self.hyper_b_1(states).view(-1, 1, self.embed_dim)
        hidden = F.elu(th.bmm(agent_qs, w1) + b1)

        w2 = th.exp(self.hyper_w_2(global_ctx)).view(-1, self.embed_dim, 1)
        b2 = self.hyper_b_2(states).view(-1, 1, 1)

        y = th.bmm(hidden, w2) + b2
        q_tot = y.view(bs, -1, 1)
        return q_tot
"""
with open("/content/pymarl/src/modules/mixers/attentive_mixer.py", "w") as f:
    f.write(amix_code)

# 注册AMixer到q_learner.py
learner_path = "/content/pymarl/src/learners/q_learner.py"
with open(learner_path, "r", encoding="utf-8") as f:
    content = f.read()

if "from modules.mixers.attentive_mixer import AMixer" not in content:
    content = re.sub(r"(from modules\.mixers\.qmix import QMixer)",
                     r"\1\nfrom modules.mixers.attentive_mixer import AMixer", content)
with open(learner_path, "w", encoding="utf-8") as f:
    f.write(content)

# AMIX配置文件(增加embed_dim以适应更复杂的网络)
amix_yaml = """action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000
runner: "episode"
buffer_size: 5000
target_update_interval: 200
agent: "rnn"
mac: "basic_mac"
agent_output_type: "q"
learner: "q_learner"
double_q: True
mixer: "amix"
mixing_embed_dim: 64
attn_heads: 4
use_residual: True
use_layer_norm: True
name: "amix"
"""
with open("/content/pymarl/src/config/algs/amix.yaml", "w") as f:
    f.write(amix_yaml)

print("AMIX架构已完成部署与注册")

#修复q_learner.py的Mixer注册逻辑与缩进
file_path = "/content/pymarl/src/learners/q_learner.py"
with open(file_path, "r", encoding="utf-8") as f:
    content = f.read()

# 匹配原始Mixer初始化代码块
pattern = re.compile(r'(\s*)(if args\.mixer == "vdn":(?:\s*self\.mixer = VDNMixer\(\))?)'
                     r'(?:\s*elif args\.mixer == "qmix":\s*self\.mixer = QMixer\(args\))?'
                     r'(?:\s*elif args\.mixer == "xmix":\s*self\.mixer = XMixer\(args\))?'
                     r'(?:\s*elif args\.mixer == "amix":\s*self\.mixer = AMixer\(args\))?'
                     r'\s*else:\s*raise ValueError\("Mixer \{\} not recognised\."\.format\(args\.mixer\)\)', re.DOTALL)

match = pattern.search(content)

if match:
    initial_indent = match.group(1)
    # 构造包含 amix 且缩进完美的逻辑块
    correct_block = f"""{initial_indent}if args.mixer == "vdn":
{initial_indent}    self.mixer = VDNMixer()
{initial_indent}elif args.mixer == "qmix":
{initial_indent}    self.mixer = QMixer(args)
{initial_indent}elif args.mixer == "amix":
{initial_indent}    self.mixer = AMixer(args)
{initial_indent}else:
{initial_indent}    raise ValueError("Mixer {{}} not recognised.".format(args.mixer))"""

    content = pattern.sub(correct_block, content)

    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)
    print("q_learner.py的Mixer注册逻辑已更新")
else:
    print("未找到Mixer初始化块")

# @title 11.强力修复 AMixer 导入与注册
import os

learner_path = "/content/pymarl/src/learners/q_learner.py"

with open(learner_path, "r", encoding="utf-8") as f:
    lines = f.readlines()

has_import = False
for line in lines:
    if "from modules.mixers.attentive_mixer import AMixer" in line:
        has_import = True
        break

if not has_import:
    lines.insert(0, "from modules.mixers.attentive_mixer import AMixer\n")

# 检查并重写Mixer选择逻辑
new_lines = []
skip = False
for line in lines:
    if 'if args.mixer == "vdn":' in line:
        # 插入完整的选择逻辑
        indent = line[:line.find('if')]
        new_lines.append(f'{indent}if args.mixer == "vdn":\n')
        new_lines.append(f'{indent}    self.mixer = VDNMixer()\n')
        new_lines.append(f'{indent}elif args.mixer == "qmix":\n')
        new_lines.append(f'{indent}    self.mixer = QMixer(args)\n')
        new_lines.append(f'{indent}elif args.mixer == "amix":\n')
        new_lines.append(f'{indent}    self.mixer = AMixer(args)\n')
        skip = True
    elif skip and 'else:' in line:
        new_lines.append(line)
        skip = False
    elif not skip:
        new_lines.append(line)

with open(learner_path, "w", encoding="utf-8") as f:
    f.writelines(new_lines)

print("补丁修复完成。")

# @title 12.修复 StarCraft II 引擎底层运行环境
import os

# 1. 强制设定星际2的根目录环境变量 (极其重要)
os.environ["SC2PATH"] = "/content/StarCraftII"
print("✅ 环境变量 SC2PATH 已设置为:", os.environ["SC2PATH"])

# 2. 赋予星际2核心引擎最高级别的执行权限
!chmod -R +x /content/StarCraftII/Versions/
print("✅ 引擎核心组件执行权限已修复！")

# 3. 安装 Linux 操作系统下运行星际2 (Headless无头模式) 必须的底层 C++ 库
print("⏳ 正在检查并安装 Linux 底层运行库...")
!apt-get update -qq
!apt-get install -y -qq libtcmalloc-minimal4
print("✅ 底层依赖包安装完成！")

# @title 13.1【AMIX 对比实验】环境自检 + 训练 + 画图 + 备份
import os
import glob
import shutil
import subprocess
import matplotlib.pyplot as plt
import sys
!{sys.executable} -m pip install tensorboard
from tensorboard.backend.event_processing.event_accumulator import EventAccumulator
from google.colab import drive

MAP_NAME = "3s_vs_5z"             # 3m, 8m, 2s3z, MMM2, 5m_vs_6m 3s_vs_5z corridor
T_MAX = 1000000
ATTN_HEADS = 4
SAVE_INTERVAL = 99000
ALG_PREFIX = f"amix_{ATTN_HEADS}head_{MAP_NAME}"

print(f"连接Google Drive，执行{MAP_NAME}地图的AMIX({ATTN_HEADS}Head)测试")
drive.mount('/content/drive')
backup_base = "/content/drive/MyDrive/毕设MARL备份"
for folder in ["Plots", f"Replays/{MAP_NAME}", "Models_and_Logs"]:
    os.makedirs(f"{backup_base}/{folder}", exist_ok=True)

subprocess.run("killall -9 SC2_x64", shell=True, stderr=subprocess.DEVNULL)
subprocess.run("chmod -R +x /content/StarCraftII/Versions/", shell=True)
subprocess.run("apt-get update -qq && apt-get install -y -qq libtcmalloc-minimal4", shell=True)


print(f"\n[1/4] 开始训练AMIX(地图:{MAP_NAME},头数:{ATTN_HEADS})")

env_vars = os.environ.copy()
env_vars["SC2PATH"] = "/content/StarCraftII"

train_cmd = f"""cd /content/pymarl/src && python3 main.py --config=amix --env-config=sc2 with \
    env_args.map_name={MAP_NAME} \
    t_max={T_MAX} \
    attn_heads={ATTN_HEADS} \
    name="{ALG_PREFIX}" \
    use_tensorboard=True \
    save_model=True \
    save_model_interval={SAVE_INTERVAL}
"""

process = subprocess.Popen(train_cmd, shell=True, env=env_vars, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
for line in process.stdout:
    print(line, end='')
process.wait()
print("训练完成")


print(f"\n[2/4] 正在解析TensorBoard绘制{MAP_NAME}胜率曲线")
tb_paths = glob.glob(f"/content/pymarl/**/tb_logs/{ALG_PREFIX}*", recursive=True)
if tb_paths:
    latest_tb = max(tb_paths, key=os.path.getmtime)
    ea = EventAccumulator(latest_tb)
    ea.Reload()
    if 'test_battle_won_mean' in ea.scalars.Keys():
        events = ea.scalars.Items('test_battle_won_mean')
        steps = [e.step for e in events]
        vals = [e.value for e in events]

        plt.figure(figsize=(8, 5))
        plt.plot(steps, vals, label=f'AMIX ({ATTN_HEADS} Head)', color='#d62728', linewidth=2.5)
        plt.title(f'Win Rate Convergence on {MAP_NAME} Map (AMIX)', fontsize=14, fontweight='bold')
        plt.xlabel('Environment Steps', fontsize=12)
        plt.ylabel('Test Battle Won Mean', fontsize=12)
        plt.ylim(-0.05, 1.05)
        plt.grid(True, linestyle='--', alpha=0.7)
        plt.legend(loc='lower right')

        plot_path = f"{backup_base}/Plots/{ALG_PREFIX}_win_rate.png"
        plt.savefig(plot_path, dpi=300, bbox_inches='tight')
        plt.show()
        print(f"已存入网盘:{plot_path}")
    else:
        print("未能找到test_battle_won_mean字段。")

print(f"\n[3/4] 正在提取{MAP_NAME}地图的历史存档，生成进化录像")

model_paths = glob.glob(f"/content/pymarl/**/models/{ALG_PREFIX}*", recursive=True)
if model_paths:
    latest_model_dir = max(model_paths, key=os.path.getmtime)
    step_folders = [d for d in os.listdir(latest_model_dir) if d.isdigit()]
    step_folders.sort(key=int)

    print(f"找到以下进化检查点:{step_folders}")
    for step in step_folders:
        print(f"正在生成第{step}步的评估录像...")
        eval_cmd = f"""cd /content/pymarl/src && python3 main.py --config=amix --env-config=sc2 with \
            env_args.map_name={MAP_NAME} \
            evaluate=True \
            save_replay=True \
            test_nepisode=1 \
            attn_heads={ATTN_HEADS} \
            checkpoint_path="{latest_model_dir}" \
            load_step={step}
        """
        subprocess.run(eval_cmd, shell=True, env=env_vars, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

        replays = glob.glob("/content/StarCraftII/Replays/**/*.SC2Replay", recursive=True)
        for rp in replays:
            new_name = f"{ALG_PREFIX}_step_{step}.SC2Replay"
            dest_path = os.path.join(backup_base, "Replays", MAP_NAME, new_name)
            shutil.copy(rp, dest_path)
            os.remove(rp)
    print("录像已分类打包网盘")

print("\n[4/4]正在将底层日志和原始模型深度备份到Google Drive...")
src_results = "/content/pymarl/results"
dest_results = f"{backup_base}/Models_and_Logs"
if os.path.exists(src_results):
    shutil.copytree(src_results, dest_results, dirs_exist_ok=True)

print(f"\n{MAP_NAME}地图AMIX测试全部完成。")

# @title 13.2【AMIX 消融实验】
import os
import re
import glob
import shutil
import subprocess
import matplotlib.pyplot as plt
import sys
!{sys.executable} -m pip install tensorboard -q
from tensorboard.backend.event_processing.event_accumulator import EventAccumulator
from google.colab import drive

MAP_NAME="3s_vs_5z"
T_MAX=1000000
SAVE_INTERVAL=99000

ATTN_HEADS=4
USE_RESIDUAL=True  # 残差连接
USE_LAYER_NORM=True # 层归一化
USE_ATTENTION=True  # 多头注意力
POOLING="max"          # 全局池化方式max/mean/sum
WEIGHT_NONNEG="exp"    # 超网络权重非负实现 exp/abs
STATE_EMBED_DEPTH="deep"  # 状态嵌入深度deep/shallow
MIXING_EMBED_DIM=64

# 版本标识
suffix_parts=[]
suffix_parts.append(f"h{ATTN_HEADS}")
if not USE_RESIDUAL: suffix_parts.append("nores")
if not USE_LAYER_NORM: suffix_parts.append("noln")
if not USE_ATTENTION: suffix_parts.append("noattn")
if POOLING!="max": suffix_parts.append(f"pool{POOLING}")
if WEIGHT_NONNEG!="exp": suffix_parts.append(WEIGHT_NONNEG)
if STATE_EMBED_DEPTH!="deep": suffix_parts.append("shallow")
version_suffix="_".join(suffix_parts) if suffix_parts else "full"
ALG_PREFIX=f"amix_{version_suffix}_{MAP_NAME}"

print("当前消融配置：")
print(f"地图={MAP_NAME} 头数={ATTN_HEADS} 残差={USE_RESIDUAL} 层归一={USE_LAYER_NORM}")
print(f"使用注意力={USE_ATTENTION} 池化={POOLING} 权值非负={WEIGHT_NONNEG}")
print(f"状态嵌入深度={STATE_EMBED_DEPTH} 实验标识={version_suffix}\n")

# 动态生成attentive_mixer.py
def build_amixer_code(use_attn, attn_heads, use_residual, use_layer_norm,
                      pooling, weight_nonneg, state_embed_depth, embed_dim):
    if pooling=="max":
        pool_line="global_ctx = ffn_out.max(dim=1)[0]"
    elif pooling=="mean":
        pool_line="global_ctx = ffn_out.mean(dim=1)"
    else:
        pool_line="global_ctx = ffn_out.sum(dim=1)"

    if weight_nonneg=="exp":
        w1_line="w1 = th.exp(self.hyper_w_1(global_ctx)).view(-1, self.n_agents, self.embed_dim)"
        w2_line="w2 = th.exp(self.hyper_w_2(global_ctx)).view(-1, self.embed_dim, 1)"
    else:
        w1_line="w1 = th.abs(self.hyper_w_1(global_ctx)).view(-1, self.n_agents, self.embed_dim)"
        w2_line="w2 = th.abs(self.hyper_w_2(global_ctx)).view(-1, self.embed_dim, 1)"

    if state_embed_depth=="deep":
        embed_block=f"""self.state_embed = nn.Sequential(
            nn.Linear(self.state_dim, {embed_dim}),
            nn.ReLU(),
            nn.Linear({embed_dim}, {embed_dim} * self.n_agents)
        )"""
    else:
        embed_block=f"self.state_embed = nn.Linear(self.state_dim, {embed_dim} * self.n_agents)"

    if use_attn:
        attn_init=f"self.attn = nn.MultiheadAttention(embed_dim=self.embed_dim, num_heads={attn_heads}, batch_first=True)"
        attn_forward="attn_out, _ = self.attn(state_repr, state_repr, state_repr)"
        residual_attn="if self.use_residual:\n            attn_out = state_repr + attn_out"
    else:
        attn_init=""
        attn_forward="attn_out = state_repr"
        residual_attn=""

    code=f'''import torch as th
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

class AMixer(nn.Module):
    def __init__(self, args):
        super(AMixer, self).__init__()
        self.args = args
        self.n_agents = args.n_agents
        self.state_dim = int(np.prod(args.state_shape))
        self.embed_dim = getattr(args, "mixing_embed_dim", {embed_dim})

        self.attn_heads = {attn_heads}
        self.use_residual = {use_residual}
        self.use_layer_norm = {use_layer_norm}

        {embed_block}

        {attn_init}

        if self.use_layer_norm:
            self.norm1 = nn.LayerNorm(self.embed_dim)
            self.norm2 = nn.LayerNorm(self.embed_dim)

        self.ffn = nn.Sequential(
            nn.Linear(self.embed_dim, self.embed_dim * 2),
            nn.ReLU(),
            nn.Linear(self.embed_dim * 2, self.embed_dim)
        )

        self.hyper_w_1 = nn.Linear(self.embed_dim, self.embed_dim * self.n_agents)
        self.hyper_w_2 = nn.Linear(self.embed_dim, self.embed_dim)

        self.hyper_b_1 = nn.Linear(self.state_dim, self.embed_dim)
        self.hyper_b_2 = nn.Sequential(
            nn.Linear(self.state_dim, self.embed_dim),
            nn.ReLU(),
            nn.Linear(self.embed_dim, 1)
        )

    def forward(self, agent_qs, states):
        bs = agent_qs.size(0)
        states = states.reshape(-1, self.state_dim)
        agent_qs = agent_qs.view(-1, 1, self.n_agents)

        state_repr = self.state_embed(states).view(-1, self.n_agents, self.embed_dim)

        {attn_forward}

        if self.use_residual and {use_attn}:
            attn_out = state_repr + attn_out
        if self.use_layer_norm:
            attn_out = self.norm1(attn_out)

        ffn_out = self.ffn(attn_out)
        if self.use_residual:
            ffn_out = attn_out + ffn_out
        if self.use_layer_norm:
            ffn_out = self.norm2(ffn_out)

        {pool_line}

        {w1_line}
        b1 = self.hyper_b_1(states).view(-1, 1, self.embed_dim)
        hidden = F.elu(th.bmm(agent_qs, w1) + b1)

        {w2_line}
        b2 = self.hyper_b_2(states).view(-1, 1, 1)

        y = th.bmm(hidden, w2) + b2
        q_tot = y.view(bs, -1, 1)
        return q_tot
'''
    return code

mixer_path="/content/pymarl/src/modules/mixers/attentive_mixer.py"
with open(mixer_path, "w") as f:
    f.write(build_amixer_code(
        use_attn=USE_ATTENTION,
        attn_heads=ATTN_HEADS,
        use_residual=USE_RESIDUAL,
        use_layer_norm=USE_LAYER_NORM,
        pooling=POOLING,
        weight_nonneg=WEIGHT_NONNEG,
        state_embed_depth=STATE_EMBED_DEPTH,
        embed_dim=MIXING_EMBED_DIM
    ))
print("已生成 attentive_mixer.py")

# 注册AMixer到q_learner.py（如果尚未注册）
learner_path="/content/pymarl/src/learners/q_learner.py"
with open(learner_path, "r", encoding="utf-8") as f:
    content=f.read()

if "from modules.mixers.attentive_mixer import AMixer" not in content:
    content=re.sub(r"(from modules\.mixers\.qmix import QMixer)",
                   r"\1\nfrom modules.mixers.attentive_mixer import AMixer", content)
    with open(learner_path, "w", encoding="utf-8") as f:
        f.write(content)

pattern=re.compile(r'(\s*)(if args\.mixer == "vdn":(?:\s*self\.mixer = VDNMixer\(\))?)'
                   r'(?:\s*elif args\.mixer == "qmix":\s*self\.mixer = QMixer\(args\))?'
                   r'(?:\s*elif args\.mixer == "xmix":\s*self\.mixer = XMixer\(args\))?'
                   r'(?:\s*elif args\.mixer == "amix":\s*self\.mixer = AMixer\(args\))?'
                   r'\s*else:\s*raise ValueError\("Mixer \{\} not recognised\."\.format\(args\.mixer\)\)', re.DOTALL)
match=pattern.search(content)
if match:
    indent=match.group(1)
    fixed_block=f"""{indent}if args.mixer == "vdn":
{indent}    self.mixer = VDNMixer()
{indent}elif args.mixer == "qmix":
{indent}    self.mixer = QMixer(args)
{indent}elif args.mixer == "amix":
{indent}    self.mixer = AMixer(args)
{indent}else:
{indent}    raise ValueError("Mixer {{}} not recognised.".format(args.mixer))"""
    content=pattern.sub(fixed_block, content)
    with open(learner_path, "w", encoding="utf-8") as f:
        f.write(content)

print("q_learner.py 注册完成")

# 挂载网盘并准备目录
drive.mount('/content/drive')
backup_base="/content/drive/MyDrive/毕设MARL备份"
for folder in ["Plots", f"Replays/{MAP_NAME}", "Models_and_Logs"]:
    os.makedirs(f"{backup_base}/{folder}", exist_ok=True)

# 环境准备
subprocess.run("killall -9 SC2_x64", shell=True, stderr=subprocess.DEVNULL)
subprocess.run("chmod -R +x /content/StarCraftII/Versions/", shell=True)
subprocess.run("apt-get update -qq && apt-get install -y -qq libtcmalloc-minimal4", shell=True)

# 开始训练
print(f"\n开始训练 {version_suffix}")
env_vars=os.environ.copy()
env_vars["SC2PATH"]="/content/StarCraftII"

train_cmd=f"""cd /content/pymarl/src && python3 main.py --config=amix --env-config=sc2 with \
    env_args.map_name={MAP_NAME} \
    t_max={T_MAX} \
    attn_heads={ATTN_HEADS} \
    use_residual={USE_RESIDUAL} \
    use_layer_norm={USE_LAYER_NORM} \
    mixing_embed_dim={MIXING_EMBED_DIM} \
    name="{ALG_PREFIX}" \
    use_tensorboard=True \
    save_model=True \
    save_model_interval={SAVE_INTERVAL}
"""

process=subprocess.Popen(train_cmd, shell=True, env=env_vars, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
for line in process.stdout:
    print(line, end='')
process.wait()
print("训练完成")

# 绘制胜率曲线
print("\n绘制胜率曲线")
tb_paths=glob.glob(f"/content/pymarl/**/tb_logs/{ALG_PREFIX}*", recursive=True)
if tb_paths:
    latest_tb=max(tb_paths, key=os.path.getmtime)
    ea=EventAccumulator(latest_tb)
    ea.Reload()
    if 'test_battle_won_mean' in ea.scalars.Keys():
        events=ea.scalars.Items('test_battle_won_mean')
        steps=[e.step for e in events]
        vals=[e.value for e in events]

        plt.figure(figsize=(8,5))
        plt.plot(steps, vals, label=f'AMIX ({version_suffix})', color='#d62728', linewidth=2.5)
        plt.title(f'Win Rate on {MAP_NAME} (AMIX)', fontsize=14, fontweight='bold')
        plt.xlabel('Environment Steps', fontsize=12)
        plt.ylabel('Test Battle Won Mean', fontsize=12)
        plt.ylim(-0.05,1.05)
        plt.grid(True, linestyle='--', alpha=0.7)
        plt.legend(loc='lower right')

        plot_path=f"{backup_base}/Plots/{ALG_PREFIX}_win_rate.png"
        plt.savefig(plot_path, dpi=300, bbox_inches='tight')
        plt.show()
        print(f"图表已存入网盘: {plot_path}")
    else:
        print("未找到 test_battle_won_mean 字段")
else:
    print("未找到 TensorBoard 日志")

# 生成录像
print("\n生成评估录像")
model_paths=glob.glob(f"/content/pymarl/**/models/{ALG_PREFIX}*", recursive=True)
if model_paths:
    latest_model_dir=max(model_paths, key=os.path.getmtime)
    step_folders=[d for d in os.listdir(latest_model_dir) if d.isdigit()]
    step_folders.sort(key=int)
    print(f"找到检查点步骤: {step_folders}")

    for step in step_folders:
        print(f"正在生成第 {step} 步的回放")
        eval_cmd=f"""cd /content/pymarl/src && python3 main.py --config=amix --env-config=sc2 with \
            env_args.map_name={MAP_NAME} \
            evaluate=True \
            save_replay=True \
            test_nepisode=1 \
            attn_heads={ATTN_HEADS} \
            use_residual={USE_RESIDUAL} \
            use_layer_norm={USE_LAYER_NORM} \
            mixing_embed_dim={MIXING_EMBED_DIM} \
            checkpoint_path="{latest_model_dir}" \
            load_step={step}
        """
        subprocess.run(eval_cmd, shell=True, env=env_vars, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

        replays=glob.glob("/content/StarCraftII/Replays/**/*.SC2Replay", recursive=True)
        for rp in replays:
            new_name=f"{ALG_PREFIX}_step_{step}.SC2Replay"
            dest_path=os.path.join(backup_base, "Replays", MAP_NAME, new_name)
            shutil.copy(rp, dest_path)
            os.remove(rp)
    print("录像已备份至网盘")

# 备份完整日志和模型
print("\n备份原始日志和模型")
src_results="/content/pymarl/results"
dest_results=f"{backup_base}/Models_and_Logs"
if os.path.exists(src_results):
    shutil.copytree(src_results, dest_results, dirs_exist_ok=True)

print(f"\n实验 {version_suffix} 全部完成")

# @title 14.对比实验：自动检索并绘制 QMIX vs AMIX (自动适配地图)
import os
import glob
import matplotlib.pyplot as plt
from tensorboard.backend.event_processing.event_accumulator import EventAccumulator

# ==========================================
# 地图配置
# ==========================================
MAP_NAME = "3s5z"  #( "8m", "2s3z", "5m_vs_6m")

# ==========================================
# 1. 定位最新日志文件夹
# ==========================================
backup_base = "/content/drive/MyDrive/毕设MARL备份/Models_and_Logs"

print(f"📂 正在网盘中自动搜索【{MAP_NAME}】地图的最新训练日志...")

# 使用 glob 深度搜索包含 qmix/amix 关键字和 map_name 的 tfevents 二进制文件
qmix_files = glob.glob(f"{backup_base}/**/tb_logs/*qmix*{MAP_NAME}*/*tfevents*", recursive=True)
amix_files = glob.glob(f"{backup_base}/**/tb_logs/*amix*{MAP_NAME}*/*tfevents*", recursive=True)

# 兼容性抢救：处理之前 8m 地图 AMIX 命名未包含地图名的情况 (例如 amix_1_head__xxx)
if MAP_NAME == "8m" and not amix_files:
    print("⚠️ 未找到标准命名的 8m AMIX 日志，启动兼容模式搜索旧版 'amix_1_head'...")
    amix_files = glob.glob(f"{backup_base}/**/tb_logs/*amix_1_head*/*tfevents*", recursive=True)

try:
    if not qmix_files:
        raise FileNotFoundError(f"❌ 找不到 {MAP_NAME} 的 QMIX 日志，请确认是否已备份。")
    if not amix_files:
        raise FileNotFoundError(f"❌ 找不到 {MAP_NAME} 的 AMIX 日志，请确认是否已备份。")

    # 取修改时间最新（max + getmtime）的那个文件，防止多次运行产生旧文件干扰
    qmix_file = max(qmix_files, key=os.path.getmtime)
    amix_file = max(amix_files, key=os.path.getmtime)

    print(f"✅ 锁定 QMIX 最新日志: {os.path.basename(os.path.dirname(qmix_file))}")
    print(f"✅ 锁定 AMIX 最新日志: {os.path.basename(os.path.dirname(amix_file))}")

    # ==========================================
    # 2. 读取并解析二进制数据
    # ==========================================
    print("⏳ 数据加载解析中，请稍候...")
    ea_qmix = EventAccumulator(qmix_file, size_guidance={'scalars': 0}).Reload()
    ea_amix = EventAccumulator(amix_file, size_guidance={'scalars': 0}).Reload()

    target = 'test_battle_won_mean'

    q_steps = [e.step for e in ea_qmix.scalars.Items(target)]
    q_vals = [e.value for e in ea_qmix.scalars.Items(target)]

    a_steps = [e.step for e in ea_amix.scalars.Items(target)]
    a_vals = [e.value for e in ea_amix.scalars.Items(target)]

    # ==========================================
    # 3. 绘制学术对比图
    # ==========================================
    plt.figure(figsize=(9, 6))

    plt.plot(q_steps, q_vals, label='QMIX (Baseline)', color='#1f77b4', linewidth=2.0, alpha=0.8)
    plt.plot(a_steps, a_vals, label='AMIX (Ours)', color='#d62728', linewidth=2.5)

    # 标题动态跟进地图名字
    plt.title(f'Performance Comparison: QMIX vs AMIX on {MAP_NAME}', fontsize=15, fontweight='bold')
    plt.xlabel('Environment Steps', fontsize=13)
    plt.ylabel('Test Battle Won Rate', fontsize=13)
    plt.ylim(-0.05, 1.05)
    plt.grid(True, linestyle='--', alpha=0.5)
    # plt.legend(loc='lower right', fontsize=12)
    plt.legend(loc='upper left', fontsize=13)

    # ==========================================
    # 4. 保存超高清图表 (动态命名)
    # ==========================================
    plot_save_dir = "/content/drive/MyDrive/毕设MARL备份/Plots"
    os.makedirs(plot_save_dir, exist_ok=True)

    # 导出的文件名也会自动带上地图名称，防止被后来的覆盖
    output_path = os.path.join(plot_save_dir, f"Final_Comparison_{MAP_NAME}.png")

    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    plt.show()

    print(f"🎉 完美！【{MAP_NAME}】对比图已生成并永久存入网盘: {output_path}")

except Exception as e:
    print(f"⚠️ 出现错误: {e}")
    print("💡 请确认 Google Drive 已挂载，且对应地图的训练数据确实存在于网盘中。")

# @title 15.消融实验“三线对比图”
import os
import glob
import matplotlib.pyplot as plt
from tensorboard.backend.event_processing.event_accumulator import EventAccumulator

MAP_NAME = "MMM2"
backup_base = "/content/drive/MyDrive/毕设MARL备份/Models_and_Logs"

qmix_logs = glob.glob(f"{backup_base}/**/tb_logs/qmix_{MAP_NAME}*/*tfevents*", recursive=True)
amix_1h_logs = glob.glob(f"{backup_base}/**/tb_logs/amix_1head_{MAP_NAME}*/*tfevents*", recursive=True)
amix_4h_logs = glob.glob(f"{backup_base}/**/tb_logs/amix_4head_{MAP_NAME}*/*tfevents*", recursive=True)
amix_8h_logs = glob.glob(f"{backup_base}/**/tb_logs/amix_8head_{MAP_NAME}*/*tfevents*", recursive=True)

if not (qmix_logs and amix_1h_logs and amix_4h_logs):
    print("找不到全部")
else:
    log_qmix = max(qmix_logs, key=os.path.getmtime)
    log_amix1 = max(amix_1h_logs, key=os.path.getmtime)
    log_amix4 = max(amix_4h_logs, key=os.path.getmtime)
    # log_amix8 = max(amix_8h_logs, key=os.path.getmtime)

    def get_data(log_path):
        ea = EventAccumulator(log_path, size_guidance={'scalars': 0}).Reload()
        events = ea.scalars.Items('test_battle_won_mean')
        return [e.step for e in events], [e.value for e in events]
    steps_q, vals_q = get_data(log_qmix)
    steps_a1, vals_a1 = get_data(log_amix1)
    steps_a4, vals_a4 = get_data(log_amix4)
    # steps_a8, vals_a8 = get_data(log_amix8)

    plt.figure(figsize=(10, 6))

    # 蓝色虚线
    plt.plot(steps_q, vals_q, label='QMIX (Baseline)', color='#1f77b4', linewidth=2.0, linestyle='--')
    # 橙色实线
    plt.plot(steps_a1, vals_a1, label='AMIX (1-Head)', color='#ff7f0e', linewidth=2.5)
    # 红色实线加粗
    plt.plot(steps_a4, vals_a4, label='AMIX (4-Head)', color='#d62728', linewidth=3.0)
    # 橙色实线
    # plt.plot(steps_a8, vals_a8, label='AMIX (8-Head)', color='#ff7f0e', linewidth=2.5)

    plt.title(f'Ablation Study of Attention Heads on {MAP_NAME} Map', fontsize=16, fontweight='bold')
    plt.xlabel('Environment Steps', fontsize=14)
    plt.ylabel('Test Battle Won Rate', fontsize=14)
    plt.ylim(-0.05, 1.05)
    plt.grid(True, linestyle='--', alpha=0.5)
    plt.legend(loc='lower right', fontsize=13)

    plot_path = f"/content/drive/MyDrive/毕设MARL备份/Plots/Ablation_{MAP_NAME}_3lines.png"
    plt.savefig(plot_path, dpi=300, bbox_inches='tight')
    plt.show()
    print(f"已生成:{plot_path}")